# Development Docker Compose - Full stack with hot reload
version: '3.8'

services:
  # Backend microservice
  backend:
    build:
      context: ../backend
      dockerfile: ../deploy/backend.Dockerfile
      target: development
    container_name: mess-ai-backend-dev
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - DATA_ROOT_DIR=/data
    volumes:
      - ../backend:/app/backend
      - ../data:/data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mess-ai-network

  # Frontend React application
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/frontend.dev.Dockerfile
    container_name: mess-ai-frontend-dev
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - mess-ai-network

networks:
  mess-ai-network:
    driver: bridge